datasets:
  - abc_atlas_wmb_thalamus
  - libd_dlpfc
  - mouse_brain_sagittal_anterior
  - mouse_brain_sagittal_posterior
  - mouse_kidney_coronal
  - osmfish_Ssp
  - SEA_AD_data
  - sotip_simulation
  - spatialDLPFC
  - STARmap_2018_mouse_cortex
  - visium_breast_cancer_SEDR
  - visium_chicken_heart
  - xenium_breast_cancer
  - xenium_mouse_brain_SergioSalas
results_dir: "/home/ubuntu/tmp_data"
