git_dir: /home/jovyan/scratch/SpaceHack2/userfolders/jsun/SpaceHack2023
results_dir: /home/jovyan/scratch/SpaceHack2/userfolders/jsun/wfTestData

datasets:
  libd_dlpfc:
    env: data/libd_dlpfc/libd_dlpfc.yml
    script: data/libd_dlpfc/libd_dlpfc.r