# Github repo path, modify based on your env
git_dir: /home/jovyan/scratch/SpaceHack2/userfolders/jsun/workflow/SpaceHack2023
# Dataset path, modify based on your env
data_dir: /home/jovyan/scratch/SpaceHack2/userfolders/jsun/workflow/libd_dlpfc

seed: 2023

# Methods to run for the pipeline, modify based on your need
use_methods:
  - "BayesSpace"
  - "maple"
  - "SEDR"
  - "scanpy"