# Metasetting for methods.smk
git_dir: /home/jovyan/scratch/SpaceHack2/userfolders/jsun/SpaceHack2023
data_dir: /home/jovyan/scratch/SpaceHack2/userfolders/jsun/wfTestData/libd_dlpfc
seed: 2023

use_methods:
  - "BayesSpace"
  - "BANKSY"
  - "SEDR"
  - "scanpy"

config_files:
  BANKSY:
    config_1: "config/config_1.json"
    config_2: "config/config_2.json"
    config_3: "config/config_3.json"
    config_4: "config/config_4.json"
    config_5: "config/config_5.json"
    config_6: "config/config_6.json"
    config_7: "config/config_7.json"
    config_8: "config/config_8.json"
  DeepST:
    config_1: "config/config_1.json"
    config_2: "config/config_2.json"
  GraphST:
    config_1: "config/config_1.json"
    config_2: "config/config_2.json"
    config_3: "config/config_3.json"
    config_4: "config/config_4.json"
    config_5: "config/config_5.json"
    config_6: "config/config_6.json"
  SCAN_IT:
    config_1: "config.json"
  SEDR:
    config_1: "config/config_1.json"
    config_2: "config/config_2.json"
    config_3: "config/config_3.json"
    config_4: "config/config_4.json"
    config_5: "config/config_5.json"
    config_6: "config/config_6.json"
  SOTIP:
    config_1: "config/config.json"
  STAGATE:
    config_1: "config/config_1.json"
    config_2: "config/config_2.json"
    config_3: "config/config_3.json"
    config_4: "config/config_4.json"
    config_5: "config/config_5.json"
    config_6: "config/config_6.json"
    config_7: "config/config_7.json"
    config_8: "config/config_8.json"
    config_9: "config/config_9.json"
    config_10: "config/config_10.json"
    config_11: "config/config_11.json"
    config_12: "config/config_12.json"
    config_13: "config/config_13.json"
    config_14: "config/config_14.json"
    config_15: "config/config_15.json"
    config_16: "config/config_16.json"
    config_17: "config/config_17.json"
    config_18: "config/config_18.json"
  SpaceFlow:
    config_1: "config/config.json"
  SpiceMix:
    config_1: "config/config_1.json"
  meringue:
    config_1: "config/config_1.json"
  scanpy:
    config_1: "configs/config_1.json"
  precast:
    config_1: "config/config_1.json"
    config_2: "config/config_2.json"
  seurat:
    config_1: "config/config_1.json"
    config_2: "config/config_2.json"
    config_3: "config/config_3.json"
    config_4: "config/config_4.json"
  spaGCN:
    config_1: "config/config_1.json"
    config_2: "config/config_2.json"
    config_3: "config/config_3.json"
    config_4: "config/config_4.json"
    config_5: "config/config_5.json"
    config_6: "config/config_6.json"
    config_7: "config/config_7.json"
    config_8: "config/config_8.json"
    config_9: "config/config_9.json"
    config_10: "config/config_10.json"
    config_11: "config/config_11.json"
    config_12: "config/config_12.json"
    config_13: "config/config_13.json"
    config_14: "config/config_14.json"
    config_15: "config/config_15.json"
    config_16: "config/config_16.json"


methods:
  BANKSY:
    env: method/BANKSY/banksy.yml
    script: method/BANKSY/banksy.r
    env_additional: method/BANKSY/banksy_env.sh
  BayesSpace:
    env: method/BayesSpace/BayesSpace.yml
    script: method/BayesSpace/BayesSpace.r
  DRSC:
    env: method/DRSC/DRSC.yml
    script: method/DRSC/DRSC.r
    env_additional: method/DRSC/drsc_env.sh
  DeepST:
    env: method/DeepST/DeepST.py
    script: method/DeepST/DeepST.yml
  GraphST:
    env: method/GraphST/GraphST.yml
    script: method/GraphST/method_GraphST.py
  SCAN_IT:
    env: method/SCAN-IT/scanit.yml
    script: method/SCAN-IT/method_scanit.py
  SEDR:
    env: method/SEDR/SEDR.yml
    script: method/SEDR/SEDR_method.py
  SOTIP:
    env: method/SOTIP/sotip.yml
    script: method/SOTIP/method_sotip.py
  STAGATE:
    env: method/STAGATE/STAGATE.yml
    script: method/STAGATE/method_STAGATE.py
  SpaceFlow:
    env: method/SpaceFlow/spaceflow.yml
    script: method/SpaceFlow/method_spaceflow.py
  SpiceMix:
    env: method/SpiceMix/SpiceMix.yml
    script: method/SpiceMix/SpiceMix.py
  maple:
    env: method/maple/maple.yml
    script: method/maple/maple.r
    env_additional: method/maple/maple_env.sh
  meringue:
    env: method/meringue/meringue.yml
    script: method/meringue/meringue.r
    env_additional: method/meringue/meringue_env.sh
  precast:
    env: method/precast/precast.yml
    script: method/precast/precast.r
    env_additional: method/precast/precast_env.sh
  scMEB:
    env: method/SC.MEB/SC.MEB.yml
    script: method/SC.MEB/SC.MEB.r
    env_additional: method/SC.MEB/scmeb_env.sh
  scanpy:
    env: method/scanpy/scanpy_env.yaml
    script: method/scanpy/method_scanpy.py
  seurat:
    env: method/seurat/seurat.yml
    script: method/seurat/seurat.r
  spaGCN:
    env: method/spaGCN/spaGCN.yml
    script: method/spaGCN/spaGCN.py

