# Github repo path, modify based on your env
git_dir: /home/jovyan/scratch/SpaceHack2/userfolders/jsun/workflow/SpaceHack_CherryPick
# Dataset path, modify based on your env
data_dir: /home/jovyan/scratch/SpaceHack2/userfolders/jsun/workflow/data/xenium-mouse-brain-SergioSalas

seed: 2023

# Methods to run for the pipeline, modify based on your need
use_methods:
  - "bass"
  - "STAGATE"
  - "BANKSY"
  - "CellCharter"
  - "DRSC"
  - "SEDR"
  - "scanpy"
  - "seurat"
#  - "spaGCN"        # need image to work
#  - "GraphST"        # Only for Visium
#  - "BayesSpace"
#  - "meringue"
#  - "SpiceMix"      # Remaining implementation
#  - "DeepST"
#  - "precast"
#  - "SpaceFlow"
#  - "SOTIP"

#  - "SC_MEB"  # error: neighbor returned 0...
#  - "maple"
#  - "stardust"
#  - "SCAN-IT"
