data_dir: "/home/ubuntu/tmp_data/libd_dlpfc"
config_files:
  spaGCN:
    config_1: "config/config_1.json"
    config_2: "config/config_2.json"
    config_3: "config/config_3.json"
    config_4: "config/config_4.json"
    config_5: "config/config_5.json"
    config_6: "config/config_6.json"
    config_7: "config/config_7.json"
    config_8: "config/config_8.json"
    config_9: "config/config_9.json"
    config_10: "config/config_10.json"
    config_11: "config/config_11.json"
    config_12: "config/config_12.json"
    config_13: "config/config_13.json"
    config_14: "config/config_14.json"
    config_15: "config/config_15.json"
    config_16: "config/config_16.json"


