# Github repo path, modify based on your env
git_dir: /work/PRTNR/CHUV/DIR/rgottar1/spatial/Cluster_Benchmark/SpaceHack_CherryPick
# Dataset path, modify based on your env
data_dir: /work/PRTNR/CHUV/DIR/rgottar1/spatial/Cluster_Benchmark/data/libd_dlpfc
seed: 2023

# Methods to run for the pipeline, modify based on your need
use_methods:
  - "bass"
  - "STAGATE"
  - "BANKSY"
  - "CellCharter"
  - "DRSC"
  - "precast"
  - "SpaceFlow"
  - "SEDR"
  - "scanpy"
  - "spaGCN"
#  - "seurat"
#  - "DeepST"         # Import error
  - "GraphST"        # Only for Visium
#  - "BayesSpace"

#  - "SpiceMix"      # Remaining implementation
#  - "SOTIP"

#  - "meringue"      # Extremely long runtime?
#  - "SC_MEB"  # error: neighbor returned 0...
#  - "maple"
#  - "stardust"
#  - "SCAN-IT"
