data_dir: "/home/ubuntu/tmp_data/libd_dlpfc"
git_dir: /home/ubuntu/workspace/SpaceHack2023

metrics:
  ARI:
    env: metric/ARI/ARI.yml
    script: metric/ARI/ARI.py
  CHAOS:
    env: metric/CHAOS/CHAOS.yml
    script: metric/CHAOS/CHAOS.r
  Calinski-Harabasz:
    env: metric/Calinski-Harabasz/Calinski-Harabasz.yml
    script: metric/Calinski-Harabasz/Calinski-Harabasz.py
  Completeness:
    env: metric/Completeness/Completeness.yml
    script: metric/Completeness/Completeness.py
  Davies-Bouldin:
    env: metric/Davies-Bouldin/Davies-Bouldin.yml
    script: metric/Davies-Bouldin/Davies-Bouldin.py
  Entropy:
    env: metric/Entropy/Entropy.yml
    script: metric/Entropy/Entropy.py
  FMI:
    env: metric/FMI/FMI.yml
    script: metric/FMI/FMI.py
  Homogeneity:
    env: metric/Homogeneity/Homogeneity.yml
    script: metric/Homogeneity/Homogeneity.py
  MCC:
    env: metric/MCC/MCC.yaml
    script: metric/MCC/MCC.py
  NMI:
    env: metric/NMI/NMI.yml
    script: metric/NMI/NMI.r
  PAS:
    env: metric/PAS/PAS.yml
    script: metric/PAS/PAS.r
  cluster-specific-silhouette:
    env: metric/cluster-specific-silhouette/cluster-specific-silhouette.yml
    script: metric/cluster-specific-silhouette/cluster-specific-silhouette.r
  domain-specific-f1:
    env: metric/domain-specific-f1/domain-specific-f1.yml
    script: metric/domain-specific-f1/domain-specific-f1.r
  jaccard:
    env: metric/jaccard/jaccard.yaml
    script: metric/jaccard/jaccard.py

