# Github repo path, modify based on your env
git_dir: /work/PRTNR/CHUV/DIR/rgottar1/spatial/Cluster_Benchmark/SpaceHack_CherryPick
# Dataset path, modify based on your env
git_dir: /work/PRTNR/CHUV/DIR/rgottar1/spatial/Cluster_Benchmark/SpaceHack_CherryPick
# Dataset path, modify based on your env
dataset_dir: "/work/PRTNR/CHUV/DIR/rgottar1/spatial/Cluster_Benchmark/data"
datasets:
  - xenium-mouse-brain-SergioSalas       # Mouse Brain
  - STARmap_plus
  - abc_atlas_wmb_thalamus
  - libd_dlpfc                            # Visium Comparison
  - visium_breast_cancer_SEDR
#  - stereoseq_developing_Drosophila_embryos_larvae
#  - "stereoseq_mouse_embryo"
  - visium_chicken_heart


use_metrics:
  - "ARI"
  - "Completeness"
  - "Entropy"
  - "FMI"
#  - "Homogeneity"
#  - "MCC"
  - "NMI"
  - "domain-specific-f1"
#  - "jaccard"
#  - "V_measure"                        #Config, GT
#  - "LISI"                             #Config, embed, GT
#  - "cluster-specific-silhouette"      #embed, no GT
#  - "Calinski-Harabasz"
#  - "Davies-Bouldin"
#  - "CHAOS"                            #phyiscal coord only
#  - "PAS"      # buggy TODO
