# Github repo path, modify based on your env
git_dir: /work/PRTNR/CHUV/DIR/rgottar1/spatial/Cluster_Benchmark/SpaceHack_CherryPick
# Dataset path, modify based on your env
data_dir: /work/PRTNR/CHUV/DIR/rgottar1/spatial/Cluster_Benchmark/data/xenium-mouse-brain-SergioSalas

use_metrics:
  - "ARI"
#  - "Completeness"
#  - "Entropy"
#  - "FMI"
#  - "Homogeneity"
#  - "MCC"
#  - "NMI"
#  - "domain-specific-f1"
#  - "jaccard"
#  - "V_measure"                        #Config, GT
#  - "LISI"                             #Config, embed, GT
#  - "cluster-specific-silhouette"      #embed, no GT
#  - "Calinski-Harabasz"
#  - "Davies-Bouldin"
#  - "CHAOS"                            #phyiscal coord only
#  - "PAS"      # buggy TODO
